import 'popper.js/dist/popper.min'
import 'jquery/dist/jquery.min'
import '@laylazi/bootstrap-rtl/dist/css/bootstrap-rtl.min.css'
import '@laylazi/bootstrap-rtl/dist/js/bootstrap.min'
import '../sass/style.scss'
